import './onebit-icon.css';
import { createIconComponent } from './components/Icon';

import BabySvg from './svg/Baby.svg';
import BankCardSvg from './svg/BankCard.svg';
import BrandSvg from './svg/Brand.svg';
import BroomSvg from './svg/Broom.svg';
import BulbSvg from './svg/Bulb.svg';
import BunkerSvg from './svg/Bunker.svg';
import BurgerSvg from './svg/Burger.svg';
import BurgerFriesSvg from './svg/BurgerFries.svg';
import BusSvg from './svg/Bus.svg';
import CancelSvg from './svg/Cancel.svg';
import CaptureSvg from './svg/Capture.svg';
import CarrotSvg from './svg/Carrot.svg';
import ChickenSvg from './svg/Chicken.svg';
import CoatOfArmsSvg from './svg/CoatOfArms.svg';
import CoatOfArmsBadgeIconSvg from './svg/CoatOfArmsBadgeIcon.svg';
import CookiesSvg from './svg/Cookies.svg';
import DeliveryBikerSvg from './svg/DeliveryBiker.svg';
import DogSvg from './svg/Dog.svg';
import FaceIdSvg from './svg/FaceId.svg';
import FemaleIconSvg from './svg/FemaleIcon.svg';
import HomeSvg from './svg/Home.svg';
import Home2Svg from './svg/Home2.svg';
import Home3Svg from './svg/Home3.svg';
import Home4Svg from './svg/Home4.svg';
import HomeNetworkSvg from './svg/HomeNetwork.svg';
import InvoiceSvg from './svg/Invoice.svg';
import IpadSvg from './svg/Ipad.svg';
import IphoneSvg from './svg/Iphone.svg';
import LockedSvg from './svg/Locked.svg';
import MaleIconSvg from './svg/MaleIcon.svg';
import MenuBarSvg from './svg/MenuBar.svg';
import MenuBar2Svg from './svg/MenuBar2.svg';
import MenuBar3Svg from './svg/MenuBar3.svg';
import MenuBar4Svg from './svg/MenuBar4.svg';
import MinusSvg from './svg/Minus.svg';
import MoneyBagDollarSvg from './svg/MoneyBagDollar.svg';
import MoneyBagNairaSvg from './svg/MoneyBagNaira.svg';
import MoreSvg from './svg/More.svg';
import NairaIconSvg from './svg/NairaIcon.svg';
import NairaSignalSvg from './svg/NairaSignal.svg';
import PaintStickSvg from './svg/PaintStick.svg';
import ParcelBikeSvg from './svg/ParcelBike.svg';
import PictureSvg from './svg/Picture.svg';
import PizzaSvg from './svg/Pizza.svg';
import PlusSvg from './svg/Plus.svg';
import RobotSvg from './svg/Robot.svg';
import SafeSvg from './svg/Safe.svg';
import SearchSvg from './svg/Search.svg';
import SignalSvg from './svg/Signal.svg';
import SowSvg from './svg/Sow.svg';
import TakeawaySvg from './svg/Takeaway.svg';
import TapeIconSvg from './svg/TapeIcon.svg';
import TickSvg from './svg/Tick.svg';
import TorchSvg from './svg/Torch.svg';
import TrashSvg from './svg/Trash.svg';
import UnlockSvg from './svg/Unlock.svg';
import User1Svg from './svg/User1.svg';
import User2Svg from './svg/User2.svg';
import UserAddSvg from './svg/UserAdd.svg';
import UserAltSvg from './svg/UserAlt.svg';
import UserCancelSvg from './svg/UserCancel.svg';
import UserMinusSvg from './svg/UserMinus.svg';
import UserSignalSvg from './svg/UserSignal.svg';
import YorubaManSvg from './svg/YorubaMan.svg';

export const OnebitBaby = createIconComponent(BabySvg, 'Baby');
export const OnebitBankCard = createIconComponent(BankCardSvg, 'BankCard');
export const OnebitBrand = createIconComponent(BrandSvg, 'Brand');
export const OnebitBroom = createIconComponent(BroomSvg, 'Broom');
export const OnebitBulb = createIconComponent(BulbSvg, 'Bulb');
export const OnebitBunker = createIconComponent(BunkerSvg, 'Bunker');
export const OnebitBurger = createIconComponent(BurgerSvg, 'Burger');
export const OnebitBurgerFries = createIconComponent(BurgerFriesSvg, 'BurgerFries');
export const OnebitBus = createIconComponent(BusSvg, 'Bus');
export const OnebitCancel = createIconComponent(CancelSvg, 'Cancel');
export const OnebitCapture = createIconComponent(CaptureSvg, 'Capture');
export const OnebitCarrot = createIconComponent(CarrotSvg, 'Carrot');
export const OnebitChicken = createIconComponent(ChickenSvg, 'Chicken');
export const OnebitCoatOfArms = createIconComponent(CoatOfArmsSvg, 'CoatOfArms');
export const OnebitCoatOfArmsBadgeIcon = createIconComponent(CoatOfArmsBadgeIconSvg, 'CoatOfArmsBadgeIcon');
export const OnebitCookies = createIconComponent(CookiesSvg, 'Cookies');
export const OnebitDeliveryBiker = createIconComponent(DeliveryBikerSvg, 'DeliveryBiker');
export const OnebitDog = createIconComponent(DogSvg, 'Dog');
export const OnebitFaceId = createIconComponent(FaceIdSvg, 'FaceId');
export const OnebitFemaleIcon = createIconComponent(FemaleIconSvg, 'FemaleIcon');
export const OnebitHome = createIconComponent(HomeSvg, 'Home');
export const OnebitHome2 = createIconComponent(Home2Svg, 'Home2');
export const OnebitHome3 = createIconComponent(Home3Svg, 'Home3');
export const OnebitHome4 = createIconComponent(Home4Svg, 'Home4');
export const OnebitHomeNetwork = createIconComponent(HomeNetworkSvg, 'HomeNetwork');
export const OnebitInvoice = createIconComponent(InvoiceSvg, 'Invoice');
export const OnebitIpad = createIconComponent(IpadSvg, 'Ipad');
export const OnebitIphone = createIconComponent(IphoneSvg, 'Iphone');
export const OnebitLocked = createIconComponent(LockedSvg, 'Locked');
export const OnebitMaleIcon = createIconComponent(MaleIconSvg, 'MaleIcon');
export const OnebitMenuBar = createIconComponent(MenuBarSvg, 'MenuBar');
export const OnebitMenuBar2 = createIconComponent(MenuBar2Svg, 'MenuBar2');
export const OnebitMenuBar3 = createIconComponent(MenuBar3Svg, 'MenuBar3');
export const OnebitMenuBar4 = createIconComponent(MenuBar4Svg, 'MenuBar4');
export const OnebitMinus = createIconComponent(MinusSvg, 'Minus');
export const OnebitMoneyBagDollar = createIconComponent(MoneyBagDollarSvg, 'MoneyBagDollar');
export const OnebitMoneyBagNaira = createIconComponent(MoneyBagNairaSvg, 'MoneyBagNaira');
export const OnebitMore = createIconComponent(MoreSvg, 'More');
export const OnebitNairaIcon = createIconComponent(NairaIconSvg, 'NairaIcon');
export const OnebitNairaSignal = createIconComponent(NairaSignalSvg, 'NairaSignal');
export const OnebitPaintStick = createIconComponent(PaintStickSvg, 'PaintStick');
export const OnebitParcelBike = createIconComponent(ParcelBikeSvg, 'ParcelBike');
export const OnebitPicture = createIconComponent(PictureSvg, 'Picture');
export const OnebitPizza = createIconComponent(PizzaSvg, 'Pizza');
export const OnebitPlus = createIconComponent(PlusSvg, 'Plus');
export const OnebitRobot = createIconComponent(RobotSvg, 'Robot');
export const OnebitSafe = createIconComponent(SafeSvg, 'Safe');
export const OnebitSearch = createIconComponent(SearchSvg, 'Search');
export const OnebitSignal = createIconComponent(SignalSvg, 'Signal');
export const OnebitSow = createIconComponent(SowSvg, 'Sow');
export const OnebitTakeaway = createIconComponent(TakeawaySvg, 'Takeaway');
export const OnebitTapeIcon = createIconComponent(TapeIconSvg, 'TapeIcon');
export const OnebitTick = createIconComponent(TickSvg, 'Tick');
export const OnebitTorch = createIconComponent(TorchSvg, 'Torch');
export const OnebitTrash = createIconComponent(TrashSvg, 'Trash');
export const OnebitUnlock = createIconComponent(UnlockSvg, 'Unlock');
export const OnebitUser1 = createIconComponent(User1Svg, 'User1');
export const OnebitUser2 = createIconComponent(User2Svg, 'User2');
export const OnebitUserAdd = createIconComponent(UserAddSvg, 'UserAdd');
export const OnebitUserAlt = createIconComponent(UserAltSvg, 'UserAlt');
export const OnebitUserCancel = createIconComponent(UserCancelSvg, 'UserCancel');
export const OnebitUserMinus = createIconComponent(UserMinusSvg, 'UserMinus');
export const OnebitUserSignal = createIconComponent(UserSignalSvg, 'UserSignal');
export const OnebitYorubaMan = createIconComponent(YorubaManSvg, 'YorubaMan');
